### ISSUE TITLE
Not avoiding sleep in my system

### ISSUE THREAD

**Issue by lf-araujo** [theswiftfox/DontNap#6]
My system: elementary OS 5.1 Hera x86_64 
Kernel: 5.0.0-37-generic

Thank you for the amazing software, however it does not seem to be working.

I installed per instructions, and activated it from wingpanel. It got visible immediately after installation, after activating it the system still sleeps regardless.

- How can I help debug this?

**Comment by theswiftfox** [comment]
Thanks for the feedback.

Can you check in "Settings -> Power" if the "Turn off display when inactive" setting changes to "never" when activating the app?
You could also use dconf to check if the system settings are correctly overwritten. You'd have to check those values:

- org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type  
- org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type

Both should change from 'suspend' to 'nothing'

If that works you could check with journalctl if you can find out from where the sleep is triggered (I may not have covered every source for different system configurations). 

I currently don't have direct access to my main linux install but will try to look into a more generic solution once I get back home. 

Kind regards and merry christmas!

**Comment by lf-araujo** [comment]
Thank you.

It seems to be awry. The "Turn off display when inactive" changes as 
expected, but the other two does not:


I used the debian version from your github page.



-- 
Honorary Clinical Lecturer | Department of Psychiatry | The University 
of Melbourne
Post Doc | Center of Data and Knowledge Integration for Health (CIDACS) 
| Salvador | Brazil
p: +55 71 988477207 | https://orcid.org/0000-0002-0952-5052 On ter, dez

**Comment by theswiftfox** [comment]
Alright, thats a start. 
Could you run wingpanel as explained [here](https://github.com/elementary/website/blob/afcbec011abcbc255f1919e458525c389ba621c9/docs/code/os-dev.md#wingpanel) and paste the output it produces when toggling the switch? 
It should hopefully show, why the values are not changing.

**Comment by lf-araujo** [comment]
Thanks,

I run it as per the instructions, the output is not too informative. 
Here are the errors that appears after running wingpanel:


```
┌─[luis][][~/Dropbox/Documentos/Coding/Nim/Learning/torrench]
└─λ wingpanel

** (wingpanel:23913): CRITICAL **: 06:59:31.792: Manager.vala:56: 
GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send 
message, 2 matched rules; type="method_call", sender=":1.814" (uid=1000 
pid=23913 comm="wingpanel " label="unconfined") 
interface="org.freedesktop.DBus.ObjectManager" 
member="GetManagedObjects" error name="(unset)" requested_reply="0" 
destination="org.bluez" (uid=0 pid=1097 
comm="/usr/lib/bluetooth/bluetoothd " label="unconfined")

** (wingpanel:23913): CRITICAL **: 06:59:44.466: Manager.vala:67: 
GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send 
message, 2 matched rules; type="method_call", sender=":1.814" (uid=1000 
pid=23913 comm="wingpanel " label="unconfined") 
interface="org.freedesktop.DBus.ObjectManager" 
member="GetManagedObjects" error name="(unset)" requested_reply="0" 
destination="org.bluez" (uid=0 pid=1097 
comm="/usr/lib/bluetooth/bluetoothd " label="unconfined")
```




-- 
Honorary Clinical Lecturer | Department of Psychiatry | The University 
of Melbourne
Post Doc | Center of Data and Knowledge Integration for Health (CIDACS) 
| Salvador | Brazil
p: +55 71 988477207 | https://orcid.org/0000-0002-0952-5052 On ter, dez

**Comment by theswiftfox** [comment]
okay. This seems like there is some other application monitoring those settings and overwriting the changes or something, as otherwise wingpanel should output an error on the command line when unable to change values...

As I am currently unable to reproduce the error on my side it is hard for me to find the root cause. However, I will keep this issue open and try to find an alternative approach to prevent sleep to work around issues like this.

In the meantime, if you are comfortable with coding a bit you could tinker with the indicator code directly as it is quite short and easy.
